[credentials]
usernames.admin.name = "admin"
usernames.admin.email = "admin@company.com"
usernames.admin.password = "$2b$12$tlOs/8U.ItKYtteeVRLfNOc.b9tdL8TZskO1vsFC8zbfhd3Cl497y" 

[cookie]
expiry_days = 1
key = "random_signature_key" 
name = "some_cookie_name"